project:
  type: site

site:
  title: Dragonstyle - Tech Blog of Charles Teague
  navbar:
    right:
      - text: "About"
        href: about.qmd
  site-url: https://www.charlesteague.com

format:
  html:
    theme: Sandstone




