project:
  type: site

site:
  title: "Charles Home Page"
  navbar:
    background: gray-100
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: litera
    toc: true
    css: styles.css



