project:
  type: site

site:
  title: Dragonstyle - Tech Blog of Charles Teague
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/dragonstyle/blog
      - icon: rss
        href: index.xml
  site-url: https://www.charlesteague.com
  repo-url: https://github.com/dragonstyle/blog
  repo-actions: [edit, issue]
  twitter-card:
    creator: "@dragonstyle"
  opengraph: true
  

format:
  html:
    theme: Sandstone




