project:
  type: site
header-includes: |
  <script data-goatcounter="https://dragonstyle.goatcounter.com/count"
    async src="//gc.zgo.at/count.js"></script>
  
  <style>
  .navbar-brand {
    display: flex;
    align-items: center;
  }
  .listing-title {
    font-weight: 600;
    font-size: 1.2em;
  }
  </style>

site:
  title: "Dragonstyle"
  navbar:
    pinned: true
    logo: dragonstyle.png
    right:
      - text: "About"
        href: about.qmd
    tools:
      - icon: github
        href: https://github.com/dragonstyle/blog
      - icon: rss
        href: index.xml
  site-url: https://www.charlesteague.com
  repo-url: https://github.com/dragonstyle/blog
  repo-actions: [edit, issue]
  twitter-card:
    creator: "@dragonstyle"
  opengraph: true
format:
  html:
    theme: 
      - yeti




