project:
  type: site
header-includes: |
  <script src="https://getinsights.io/js/insights.js"></script>
  <script>
  // Initialize for your project,
  // you can find this on your dashboard
  insights.init("bWUDOYx7R1EJ4HWc")
  
  // ...
  
  // track page views
  insights.trackPages()
  </script>
  
  <style>
  .navbar-brand {
    display: flex;
    align-items: center;
  }
  .listing-title {
    font-weight: 600;
    font-size: 1.2em;
  }
  </style>

site:
  title: "Dragonstyle"
  navbar:
    logo: dragonstyle.png
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/dragonstyle/blog
      - icon: rss
        href: index.xml
  site-url: https://www.charlesteague.com
  repo-url: https://github.com/dragonstyle/blog
  repo-actions: [edit, issue]
  twitter-card:
    creator: "@dragonstyle"
  opengraph: true
format:
  html:
    theme: 
      - yeti




