---
title: Transition 2
date: 9/8/2008
categories:
  - Venture Capital
  - iPhone
  - News
---

So on to part 2. After a couple of years focused on Windows Live Writer and blogging, the time has come for me to  work on something new.

I’m now a Technologist in Residence at General Catalyst, a position which will offer me a significant opportunity to learn from some very bright people with both great operational experience and also great experience in the venture capital community. This brings with it a whole new host of professional challenges, as in the short term I’ll likely be spending a lot less time actually building products and getting them to market (which is what is really natural for me). That said, it’s a set of challenges that I’m really looking forward to.

As a part of the transition, my family and I have also relocated from the Seattle area to the Boston area. After living and working here for 10 years prior to my time at Microsoft, it feels great to be back. Just in time for the MLB playoffs too. I had a great time working at Microsoft, a career objective of mine from way back has now been checked off the list :).

If you’re in the Boston area and I haven’t yet reached out to offer to buy you a cup of coffee and chat, please drop me a line!